"""add master_status enum and working_hour_is_active

Revision ID: 08fbbef38349
Revises: 9a9c2edb119f
Create Date: 2026-09-24 12:54:30.971660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fbbef38349'
down_revision: Union[str, None] = '9a9c2edb119f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='masterstatus'), nullable=False, server_default='ACTIVE'))

    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('master_profiles', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
